spring:
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tsh
    password: 123456
    url: jdbc:mysql://quotor-mysql:3306/three_bears?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    type: mysql
sleuth:
  enabled: true
